name: Windows

env:
  CONAN_REPOSITORY: https://api.bintray.com/conan/triluxitz/LiveLink_App
  CONAN_REPOSITORY_NAME: trilux
  CONAN_PACKAGE_NAME: libressl
  CONAN_USER: trilux
  CONAN_CHANNEL: stable
  CONAN_REPO_USER: jenkins@triluxitz

on:
  create:
    ref_type: tag

jobs:

  x86_64-Release:
    runs-on: windows-2019
    env:
      GITHUB_OS_NAME: windows
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}
    - name: checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(echo ${GITHUB_REF:10})
      shell: bash
    - name: install and setup conan
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-setup.ps1
      shell: powershell
    - name: create conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\build-windows.ps1 -ARCH x86_64 -BUILD_TYPE Release
      shell: powershell
    - name: deploy conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-deploy.ps1
      shell: powershell

  x86_64-Debug:
    runs-on: windows-2019
    env:
      GITHUB_OS_NAME: windows
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}
    - name: checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(echo ${GITHUB_REF:10})
      shell: bash
    - name: install and setup conan
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-setup.ps1
      shell: powershell
    - name: create conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\build-windows.ps1 -ARCH x86_64 -BUILD_TYPE Debug
      shell: powershell
    - name: deploy conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-deploy.ps1
      shell: powershell

  x86-Release:
    runs-on: windows-2019
    env:
      GITHUB_OS_NAME: windows
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}
    - name: checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(echo ${GITHUB_REF:10})
      shell: bash
    - name: install and setup conan
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-setup.ps1
      shell: powershell
    - name: create conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\build-windows.ps1 -ARCH x86 -BUILD_TYPE Release
      shell: powershell
    - name: deploy conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-deploy.ps1
      shell: powershell

  x86-Debug:
    runs-on: windows-2019
    env:
      GITHUB_OS_NAME: windows
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}
    - name: checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive
    - name: get version from tag
      run: echo ::set-env name=LIBRARY_VERSION::$(echo ${GITHUB_REF:10})
      shell: bash
    - name: install and setup conan
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-setup.ps1
      shell: powershell
    - name: create conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\build-windows.ps1 -ARCH x86 -BUILD_TYPE Debug
      shell: powershell
    - name: deploy conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-deploy.ps1
      shell: powershell
